{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
  
{{include file="field_select.tpl" field=$headimg}}

{{include file="field_yesno.tpl" field=$headimghome}}

<div class="buttonbar">
	<input type="submit" value="{{$submit}}" name="blog-settings-submit" />
</div>

