{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<div class="wp-caption alignleft contact dropmenu" style="width: 100px;">
        <a href="{{$contact.url}}" title="{{$contact.img_hover}}" /><img class="wp-image-59" src="{{$contact.thumb}}" {{$contact.sparkle}} alt="{{$contact.name}}" /></a>
        <p class="gallery-caption">{{$contact.name}}</p>
        {{if $contact.photo_menu}}
        <ul  class="menu-popup">
                {{$contact.photo_menu}}
        </ul>
        {{/if}}
</div>
