{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<section class="entry-content">
<h1 class="entry-title">{{$header}}{{if $total}} <small>({{$total}})</small>{{/if}}</h1>

    {{if $finding}}<h4>{{$finding}}</h4>{{/if}}

    <div class="buttonbar">
        <form id="contacts-search-form" action="{{$cmd}}" method="get" >
            <span class="contacts-search-desc">{{$desc}}</span>
            <input type="text" name="search" id="contacts-search" class="search-input" onfocus="this.select();" value="{{$search}}" />
            <input type="submit" name="submit" id="contacts-search-submit" value="{{$submit}}" />
        </form>
    </div>
    
    {{$tabs}}


    {{foreach $contacts as $contact}}
        {{include file="contact_template.tpl"}}
    {{/foreach}}
    <div id="contact-edit-end"></div>

    {{$paginate}}


</section>

