{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<section class="entry-content">
<h1  class="entry-title">{{$title}}</h1>


<form action="settings/features" method="post" autocomplete="off">
<input type='hidden' name='form_security_token' value='{{$form_security_token}}'>

{{foreach $features as $f}}
<h2 class="settings-heading">{{$f.0}}</h2>

{{foreach $f.1 as $fcat}}
	{{include file="field_yesno.tpl" field=$fcat}}
{{/foreach}}
{{/foreach}}

<div class="buttonbar" >
<input type="submit" name="submit" class="settings-features-submit" value="{{$submit}}" />
</div>

</form>
</section>

