{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<section class="entry-content">
<h1 class="entry-title">{{$title}}</h1>


<form action="settings/oauth" method="post" autocomplete="off">
<input type='hidden' name='form_security_token' value='{{$form_security_token}}'>


<a class="button" href="{{$baseurl}}/settings/oauth/add">{{$add}}</a>

	{{foreach $apps as $app}}
	<div class='oauthapp'>
		<img src='{{$app.icon}}' class="{{if $app.icon}} {{else}}noicon{{/if}}">
		<p>{{if $app.name}}{{$app.name}}{{else}}{{$noname}}{{/if}}</p>
		{{if $app.my}}
			{{if $app.oauth_token}}
			<button class="button"  type="submit" name="remove" value="{{$app.oauth_token}}">{{$remove}}</button>
			{{/if}}
		{{/if}}
		{{if $app.my}}
		<a href="{{$baseurl}}/settings/oauth/edit/{{$app.client_id}}" class="button">{{$edit}}</a>
		<a href="{{$baseurl}}/settings/oauth/delete/{{$app.client_id}}?t={{$form_security_token}}" class="button">{{$delete}}</a>
		{{/if}}		
	</div>
	{{/foreach}}

</form>
</section>