{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
<section class="entry-content">
<h1 class="entry-title">{{$title}}</h1>


{{foreach $options as $o}}
<dl>
    <dt><a href="{{$baseurl}}/{{$o.0}}">{{$o.1}}</a></dt>
    <dd>{{$o.2}}</dd>
</dl>
{{/foreach}}
</section>